### ISSUE TITLE
VG Surject producing CIGARs with 0 length ops

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#1528]
@adamnovak @ekg @jeizenga 
The latest version of `vg surject` is producing malformed BAM files again.
I'm getting the following error when running any of the BAM files through picards `ReorderSam` program. I redacted the read name for privacy.

I'm running picards `ValidateSamFile` on the BAMs now to get more information.

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Read name [REDACTED] , CIGAR element with zero length
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:451)
        at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:253)
        at htsjdk.samtools.SAMRecord.getAlignmentEnd(SAMRecord.java:603)
        at htsjdk.samtools.SAMRecord.computeIndexingBin(SAMRecord.java:1547)
        at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2054)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:811)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
        at picard.sam.ReorderSam.writeReads(ReorderSam.java:170)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:132)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Comment by cmarkello** [comment]
@ekg @jeizenga 
So I'm getting `ERROR:INVALID_CIGAR` errors from `ValidateSamFile` output. Likely due to the CIGAR strings with zero length which seems to be all of the invalid cigar string errors.

**Comment by cmarkello** [comment]
@ekg @jeizenga 
As a side note, should we start implementing unit tests for vg surject just to make sure further changes don't unintentionally break core functionality? Or will vg surject change significantly within the next few weeks that the unit tests would need to be continuously updated?

**Comment by adamnovak** [comment]
It would definitely make sense to have some tests for these things. They
might best be placed in the Bash-TAP tests: we can actually run the `vg
surject` command and validate the resulting BAM with the BAM validation
tool you are using. It might need to be on a small subgraph though.

On Wed, Mar 14, 2018 at 11:41 AM, Charles Markello <notifications@github.com

**Comment by ekg** [comment]
There are bash-tap tests for vg surject. This issue was not included as it's new. It was triggered by me merging empty alignments together and not normalizing the result properly, which is something I'm doing so that I don't break . I didn't notice it downstream as most variant callers will just ignore 0-length cigar elements.

If samtools has a format validator then we could apply it, as we're already depending on samtools for some tests. I don't really like the idea of putting picard tools into the test dependencies.

**Comment by ekg** [comment]
Sambamba, samtools, htslib and freebayes never complained. But Picard tools
should be supported. Are you just sorting with Picard tools?

The fix is in master.

**Comment by ekg** [comment]
I'm concerned about depending on Picard tools and Java for the bash tap
tests. Is there a smaller validation tool we could use?

**Comment by cmarkello** [comment]
So what I'm mainly doing is using picard's `ReorderSam` to reorder the
records in the surjected BAM files to follow chr1, chr2, chr3 ... etc.
order instead of the (default?) ordering of chr1, chr11, chr12 ... etc.
since it appears that the way the Dragen box (
http://edicogenome.com/dragen-bioit-platform/) that I'm using to do fast
joint genotyping on has it's own indexing scheme for the reference sequence
which apparently requires the BAM files to be ordered in the same way.

It's simply just an easy way to sort and deal with BAM files. Picard's
`ValidateSamFile` seems to also be reliably robust enough in picking up
common errors in BAM file formats. I think it might be worth supporting
just for the sake of more complete QA for the surject output.

**Comment by ekg** [comment]
I don't think chr1 chr10 chr11 ... is default. I'm not sure what settings
to what sorting algorithm cause that. I use sambamba, which appears to
order the chromosomes 1, 2, 3, ...

I'm worried that adding picard tools just for it's validator will add
another dependency (on Picard) and a more painful one (on java). If we can
find a validator that is based on htslib then I'd be less concerned about
it. Also we could add this to Jenkins, I'm mostly worried about putting it
into the bash tap tests that people will run when they build vg on their
system.

**Comment by cmarkello** [comment]
I agree, depending on java would be a pain. I'll be sure to use a different
BAM reordering program.
