### ISSUE TITLE
gfa import fails on path import

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1858]
Please describe:

1. What you were trying to do

I'm trying to import a gfa file that contains an alignemnt of 4 full chromosome sequences.

2. What you wanted to happen

Convert it into a vg graph.

3. What actually happened

The import fails with a segfault without further information. When I remove all the path from the gfa the import works. The import with the path for with just Seq3 works as well. I checked the 

4. What data and command line to use to make the problem recur, if applicable

```
vg view -v -F importGraph.gfa > importGraph.vg
```
The file can be downloaded [here](https://owncloud.tuebingen.mpg.de/index.php/s/WTnGi9tEWnC34Hr)

gdp output:
```
0x000000000165aa5f in ____strtoll_l_internal ()
```
```
(gdb) where
#0  0x000000000165aa5f in ____strtoll_l_internal ()
#1  0x0000000000a3c34e in atol (__nptr=<optimized out>) at /usr/include/stdlib.h:285
#2  gfak::custom_key::operator() (rhs=..., lhs=..., this=0x7ffdc678eff0) at /ebio/abt6_projects9/abt6_software/bin/vg/include/gfakluge.hpp:38
#3  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> >, gfak::custom_key, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> > >::_M_lower_bound (__k=..., __y=0x7ffdc678eff8, __x=0x27fe4050, this=0x7ffdc678eff0) at /usr/include/c++/5/bits/stl_tree.h:1628
#4  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> >, gfak::custom_key, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> > >::lower_bound (__k=..., this=0x7ffdc678eff0) at /usr/include/c++/5/bits/stl_tree.h:1091
#5  std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, gfak::sequence_elem, gfak::custom_key, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> > >::lower_bound (__x=..., this=0x7ffdc678eff0)
    at /usr/include/c++/5/bits/stl_map.h:916
#6  std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, gfak::sequence_elem, gfak::custom_key, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gfak::sequence_elem> > >::operator[] (this=0x7ffdc678eff0, __k=...)
    at /usr/include/c++/5/bits/stl_map.h:479
#7  0x0000000000eeab2e in gfak::GFAKluge::parse_gfa_file (this=this@entry=0x7ffdc678ef20, instream=...) at src/gfakluge.cpp:371
#8  0x0000000000a32c3e in vg::gfa_to_graph (in=..., graph=0x3ad8000, only_perfect_match=only_perfect_match@entry=false) at src/gfa.cpp:201
#9  0x000000000085d547 in <lambda(std::istream&)>::operator() (in=..., __closure=0x7ffdc678fd30) at src/subcommand/view_main.cpp:452
#10 std::_Function_handler<void(std::basic_istream<char, std::char_traits<char> >&), main_view(int, char**)::<lambda(std::istream&)> >::_M_invoke(const std::_Any_data &, std::basic_istream<char, std::char_traits<char> > &) (__functor=..., __args#0=...) at /usr/include/c++/5/functional:1871
#11 0x0000000000963d8e in std::function<void (std::istream&)>::operator()(std::istream&) const (__args#0=..., this=0x7ffdc678fd30) at /usr/include/c++/5/functional:2267
#12 vg::get_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)>) (file_name=..., callback=...) at src/utility.cpp:354
#13 0x000000000086094e in main_view (argc=5, argv=0x7ffdc6790148) at src/subcommand/view_main.cpp:456
#14 0x0000000000852b18 in std::function<int (int, char**)>::operator()(int, char**) const (__args#1=0x7ffdc6790148, __args#0=5, this=<optimized out>) at /usr/include/c++/5/functional:2267
#15 vg::subcommand::Subcommand::operator() (this=<optimized out>, argc=argc@entry=5, argv=argv@entry=0x7ffdc6790148) at src/subcommand/subcommand.cpp:72
#16 0x000000000040a597 in main (argc=5, argv=0x7ffdc6790148) at src/main.cpp:61
```
```
(gdb) list
31
32           vg::subcommand::Subcommand::for_each(vg::subcommand::PIPELINE, [](const vg::subcommand::Subcommand& command) {
33              // Announce every subcommand we have
34
35              // Pad all the names so the descriptions line up
36              string name = command.get_name();
37              name.resize(14, ' ');
38              cerr << "  -- " << name << command.get_description() << endl;
39           });
40

```

**Comment by ChriKub** [comment]
I tried to find the position in the path that causes the fail. It's a different position in every path. In the graph itself and also in the position within the path. The graph seems to be completely normal there as well.

**Comment by edawson** [comment]
I ran your GFA file through GFAlint, which reported it's fine. It's a bug in my parser.

I was passing a char array to a function that wanted a pointer. While this should have worked, it clearly didn't. I'm not sure why it only failed sometimes, but it seems to work on your graph now.

I'll let you know when it gets merged into master.

**Comment by ChriKub** [comment]
thanks @edawson

**Comment by faithokamoto** [comment]
I don't know if this ever got fixed, but I do know I can't test it now since the file seems to have gone missing. In any case the issue is stale.
