### ISSUE TITLE
Potential memory issue during distance indexing of cactus-HPRC pangenome

### ISSUE THREAD

**Issue by jmonlong** [vgteam/vg#3155]
I was trying to make the distance index for a human pangenome (made by cactus on the HPRC data). This step is taking much more memory than for other indexes and it's currently the only index that I can't produce on this HPRC data. The resource usage might suggest some problem when handling this graph.

My latest run on an instance with 480Gb mem started smoothly. I was checking the memory usage with `top` and saw it increase steadily to about 50% usage. Then for about 20h it plateaued there (always one core being apparently busy). Then It was killed, I think because of an out-of-memory signal (137).

I was using vg v1.29.0 and ran:

```
vg index -t 16 -j GRCh38-freeze1.cactus.dec31.dist -s GRCh38-freeze1.cactus.dec31.trivial.snarls GRCh38-freeze1.cactus.dec31.xg
```

The files are available in our S3 buckets:

- s3://vg-k8s/vgamb/wg/cactus/dec31/map/GRCh38-freeze1.cactus.dec31.trivial.snarls
- s3://vg-k8s/vgamb/wg/cactus/dec31/map/GRCh38-freeze1.cactus.dec31.xg

**Comment by ekg** [comment]
Is it possible to make the XG and GCSA2 indexes? Then you could use mpmap
or map as a stop-gap.

**Comment by adamnovak** [comment]
This appears to be what it's doing with 1 core and 220 GB of memory, from the 10 GB xg and the 1 GB of snarls:
```
#0  0x0000000000d73289 in std::operator==<long long, bool> (__x=..., __x=..., __y=..., __y=...) at /public/home/anovak/.local/include/c++/8.1.0/bits/hashtable_policy.h:434
#1  std::equal_to<std::pair<long long, bool> >::operator() (this=0x7fffffffaf30, __y=..., __x=...) at /public/home/anovak/.local/include/c++/8.1.0/bits/stl_function.h:356
#2  std::__detail::_Equal_helper<std::pair<long long, bool>, std::pair<long long, bool>, std::__detail::_Identity, std::equal_to<std::pair<long long, bool> >, unsigned long, true>::_S_equals (__eq=..., 
    __extract=..., __n=<optimized out>, __c=<optimized out>, __k=...) at /public/home/anovak/.local/include/c++/8.1.0/bits/hashtable_policy.h:1452
#3  std::__detail::_Hashtable_base<std::pair<long long, bool>, std::pair<long long, bool>, std::__detail::_Identity, std::equal_to<std::pair<long long, bool> >, std::hash<std::pair<long long, bool> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, true, true> >::_M_equals (this=0x7fffffffaf30, __n=0x7fd98aa9c480, __c=3085354764, __k=...)
    at /public/home/anovak/.local/include/c++/8.1.0/bits/hashtable_policy.h:1833
#4  std::_Hashtable<std::pair<long long, bool>, std::pair<long long, bool>, std::allocator<std::pair<long long, bool> >, std::__detail::_Identity, std::equal_to<std::pair<long long, bool> >, std::hash<std::pair<long long, bool> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::count (
    this=this@entry=0x7fffffffaf30, __k=...) at /public/home/anovak/.local/include/c++/8.1.0/bits/hashtable.h:1477
#5  0x00000000012d367f in std::unordered_set<std::pair<long long, bool>, std::hash<std::pair<long long, bool> >, std::equal_to<std::pair<long long, bool> >, std::allocator<std::pair<long long, bool> > >::count (__x=..., this=0x7fffffffaf30) at src/min_distance.cpp:854
#6  vg::MinimumDistanceIndex::populate_snarl_index(handlegraph::HandleGraph const*, vg::SnarlManager const*, vg::NetGraph const&, vg::Snarl const*, bool, unsigned long, vg::hash_set<std::pair<long long, bool> >&, unsigned long, unsigned long) () at src/min_distance.cpp:854
#7  0x00000000012d5390 in vg::MinimumDistanceIndex::calculate_min_index(handlegraph::HandleGraph const*, vg::SnarlManager const*, std::vector<std::pair<vg::Snarl const*, bool>, std::allocator<std::pair<vg::Snarl const*, bool> > > const*, unsigned long, bool, bool, unsigned long, unsigned long) () at src/min_distance.cpp:556
#8  0x00000000012d487c in vg::MinimumDistanceIndex::populate_snarl_index(handlegraph::HandleGraph const*, vg::SnarlManager const*, vg::NetGraph const&, vg::Snarl const*, bool, unsigned long, vg::hash_set<std::pair<long long, bool> >&, unsigned long, unsigned long) () at src/min_distance.cpp:905
#9  0x00000000012d5390 in vg::MinimumDistanceIndex::calculate_min_index(handlegraph::HandleGraph const*, vg::SnarlManager const*, std::vector<std::pair<vg::Snarl const*, bool>, std::allocator<std::pair<vg::Snarl const*, bool> > > const*, unsigned long, bool, bool, unsigned long, unsigned long) () at src/min_distance.cpp:556
#10 0x00000000012d933b in vg::MinimumDistanceIndex::MinimumDistanceIndex(handlegraph::HandleGraph const*, vg::SnarlManager const*, long) () at src/min_distance.cpp:87
#11 0x0000000000f5370d in main_index(int, char**) () at src/subcommand/index_main.cpp:704
#12 0x0000000000fd6618 in std::function<int (int, char**)>::operator()(int, char**) const (__args#1=<optimized out>, __args#0=<optimized out>, this=0x22848e8 <vg_construct+72>)
    at /public/home/anovak/.local/include/c++/8.1.0/bits/std_function.h:260
#13 vg::subcommand::Subcommand::operator() (this=this@entry=0x22848a0 <vg_construct>, argc=argc@entry=9, argv=argv@entry=0x7fffffffd738) at src/subcommand/subcommand.cpp:75
#14 0x0000000000aac49e in main () at src/main.cpp:81
#15 0x00007ffff3be6555 in __libc_start_main () from /usr/lib64/libc.so.6
#16 0x0000000000acb177 in _start () at src/main.cpp:90
```

If we really want to profile the memory, jemalloc has built-in memory profiling that I think we can use.

@xchang1 Is this about how much memory this part of distance index construction ought to take?

**Comment by adamnovak** [comment]
At scrum we decided giant snarls might just take O(n^2) memory until Distance Index 2.

**Comment by jmonlong** [comment]
In case it helps, the memory usage I experienced in the past:

| graph | distance index | giraffe mapping | 
|- | - | - |
| cactus HPRC chr20 | 14 to 145Gb | 4 to 37 Gb | 
| cactus HPRC chr2 | 90Gb | 40Gb | 
| Combined SV graph | 127Gb | 55 Gb |

Like we said at scrum, the distance indexing does use more memory than giraffe (which loads the dist index in memory if I understood correctly)

**Comment by xchang1** [comment]
That seems like too much memory. Another problem might be that the snarls are too deeply nested. I have two fixes that I want to add for Distance Index 2

- Make the construction algorithm less recursive, or at least recurse on child snarls before making big priority queues and stuff
- For large snarls, only store the distances from each node to the boundary nodes, and then for distance calculations that need the distance between nodes in a snarl (which shouldn't be too often), just do a traversal to find the shortest path

**Comment by adamnovak** [comment]
My attempt to run this from Friday is still going. It has used 424.6g of memory and about 92 CPU hours.

**Comment by faithokamoto** [comment]
We've since updated several distance index versions which decrease memory usage.
