### ISSUE TITLE
Missleading error message when vcf.gz file not present

### ISSUE THREAD

**Issue by jjfarrell** [vgteam/vg#344]
The vcf file does not exist but instead the error message is about bgzip.

vg construct  -r chr11.fasta  -v not_a_file.vcf.gz   >chr11.vg
[tabix++] was bgzip used to compress this file? not_a_file.vcf.gz

It looks like a test for file existence is needed.

**Comment by adamnovak** [comment]
We already have error checking:

```
        vcflib::VariantCallFile variant_file;
        if (!vcf_file_name.empty()) {
            variant_file.open(vcf_file_name);
            if (!variant_file.is_open()) {
                cerr << "error:[vg construct] could not open" << vcf_file_name << endl;
                return 1;
            }
        }
```

Unfortunately it looks like tabix is somehow getting in there and taking it upon itself to exit our program for us:

```
Breakpoint 3, Tabix::Tabix (this=0xc18050, file="small/x.vcf.gz") at tabix.cpp:14
14	        cerr << "[tabix++] was bgzip used to compress this file? " << file << endl;
(gdb) bt
#0  Tabix::Tabix (this=0xc18050, file="small/x.vcf.gz") at tabix.cpp:14
#1  0x0000000000467bb1 in openTabix (filename="small/x.vcf.gz", this=0x7fffffffd340)
    at /cluster/home/anovak/build/vg/include/Variant.h:106
#2  vcflib::VariantCallFile::open (this=this@entry=0x7fffffffd340, filename="small/x.vcf.gz")
    at /cluster/home/anovak/build/vg/include/Variant.h:91
#3  0x000000000045c07b in main_construct (argc=argc@entry=6, argv=argv@entry=0x7fffffffdc78) at src/main.cpp:6913
#4  0x00000000004160e4 in main (argc=6, argv=0x7fffffffdc78) at src/main.cpp:7027
```

We shall have to work around it, maybe with our own existence pre-check.
