### ISSUE TITLE
genotyper dies when single threaded

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#404]
I'm working up a simple test.

We simulate several SNPs. They should be detectable:

```
vg construct -r tiny/tiny.fa >flat.vg
vg index -x flat.xg -g flat.gcsa -k 8 flat.vg
(echo '>flat1'; vg sim -n 1 -l 50 -e 0.05 -s 69 -x flat.xg ) >flat1.fa
vg sim -n 1 -l 50 -e 0.05 -s 69 -x flat.xg -a >flat1.fa.gam
vg construct -r flat1.fa >flat1.vg
vg index -x flat1.xg flat1.vg
vg sim -n 30 -l 50 -e 0.005 -s 7372 -x flat1.xg -a >flat1.sim
(echo '>flat2'; vg sim -n 1 -l 50 -e 0.05 -s 77 -x flat.xg ) >flat2.fa
vg sim -n 1 -l 50 -e 0.05 -s 77 -x flat.xg -a >flat2.fa.gam
vg construct -r flat2.fa >flat2.vg
vg index -x flat2.xg flat2.vg
vg sim -n 30 -l 50 -e 0.005 -s 8675309 -x flat2.xg -a >flat2.sim
vg map -x flat.xg -g flat.gcsa -G <(cat flat1.sim flat2.sim) >flat.gam
vg index -d flat.gam.index -N flat.gam
```

Now this will segfault:

```
vg genotype flat.vg flat.gam.index -v -t 1
```

You may want to work from https://github.com/vgteam/vg/pull/403 to reproduce.

Backtrace:

```
#0  malloc_consolidate (av=av@entry=0x7ffff6284b20 <main_arena>) at malloc.c:4168
#1  0x00007ffff5f4255e in _int_malloc (av=av@entry=0x7ffff6284b20 <main_arena>, bytes=bytes@entry=1152) at malloc.c:3451
#2  0x00007ffff5f445a4 in __GI___libc_malloc (bytes=1152) at malloc.c:2914
#3  0x00007ffff6a58e78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00000000005957b4 in __gnu_cxx::new_allocator<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > > >::allocate (this=0x7fffffffbd80, __n=<optimized out>) at /usr/include/c++/5/ext/new_allocator.h:104
#5  std::allocator_traits<std::allocator<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > > > >::allocate (__a=..., __n=<optimized out>) at /usr/include/c++/5/bits/alloc_traits.h:491
#6  std::_Vector_base<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > >, std::allocator<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > > > >::_M_allocate (this=0x7fffffffbd80, __n=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:170
#7  std::vector<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > >, std::allocator<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > > > >::_M_emplace_back_aux<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > const&>(vg::Alignment&&, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > const&) (this=this@entry=0x7fffffffbd80) at /usr/include/c++/5/bits/vector.tcc:412
#8  0x0000000000590bf3 in std::vector<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > >, std::allocator<std::pair<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > > > >::emplace_back<vg::Alignment, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > const&>(vg::Alignment&&, std::vector<vg::Genotyper::Affinity, std::allocator<vg::Genotyper::Affinity> > const&) (this=<optimized out>) at /usr/include/c++/5/bits/vector.tcc:101
#9  vg::Genotyper::genotype_site (this=0x7fffffffc450, graph=..., site=..., superbubble_paths=std::vector of length 2, capacity 2 = {...}, affinities=std::map with 59 elements = {...}) at src/genotyper.cpp:838
#10 0x000000000045a310 in main_genotype () at src/main.cpp:1918
#11 0x00007ffff64adfa4 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#12 0x00007ffff64b1dfb in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#13 0x00007ffff64b0889 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#14 0x0000000000459883 in main_genotype (argc=argc@entry=7, argv=argv@entry=0x7fffffffe238) at src/main.cpp:1870
#15 0x0000000000413b48 in main (argc=7, argv=0x7fffffffe238) at src/main.cpp:8226
```

**Comment by ekg** [comment]
There also appears to be a race condition with one of two SNPs in my test being lost occasionally.

**Comment by adamnovak** [comment]
I'm going to try and fix this.

**Comment by adamnovak** [comment]
OK I've squished a slightly-out-of-bounds write in my PL code and added checking so it won't happen again. My theory is that I was hitting some of the block metadata used by malloc, meaning everythign would be fine until the next memory allocation that wanted to look at that block.

I've been looping the example for a while now and haven't managed to make it segfault again.

**Comment by adamnovak** [comment]
This should be fixed. (At least the segfault. Not sure about the race condition.)
